variables:
  IMAGE_TAG: "$CI_COMMIT_REF_NAME"
  REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE"

stages:
  - build
  - publish
  - deploy

test-docker:
  stage: build
  tags:
    - docker-perso
  image: docker:29.1.2
  script:
    - docker version
    - docker info
    - docker ps

docker-build:
  stage: build
  image: docker:29.1.2
  tags:
    - docker-perso
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

    - docker build -t "$REGISTRY_IMAGE/frontend:$IMAGE_TAG" frontend
    - docker build -t "$REGISTRY_IMAGE/backend:$IMAGE_TAG" backend
  only:
    - prod-hugo

docker-publish:
  stage: publish
  image: docker:29.1.2
  tags:
    - docker-perso
  needs:
    - docker-build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

    - docker push "$REGISTRY_IMAGE/frontend:$IMAGE_TAG"
    - docker push "$REGISTRY_IMAGE/backend:$IMAGE_TAG"
    - echo "$REGISTRY_IMAGE/backend:$IMAGE_TAG" and "$REGISTRY_IMAGE/frontend:$IMAGE_TAG" are availaibles
  only:
    - prod-hugo

deploy-prod:
  stage: deploy
  image: alpine:3.20
  tags:
    - docker-perso
  needs:
    - docker-publish
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - >
      ssh "$DEPLOY_USER@$DEPLOY_HOST" "
        set -e;
        cd /opt/ontozipe;
        echo '$CI_REGISTRY_PASSWORD' | docker login '$CI_REGISTRY' -u '$CI_REGISTRY_USER' --password-stdin;
        docker compose pull;
        docker compose up -d --remove-orphans;
        docker image prune -f
      "
  only:
    - prod-hugo  